version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm test
